### ISSUE TITLE
How can I fix this issue

### ISSUE THREAD

**Issue by Ruchir317** [brandongallagher1999/1337x-Bot-Go#13]
![image](https://user-images.githubusercontent.com/66352423/161392190-62b9c243-bf91-4cdd-a619-b492c513a9ff.png)

**Comment by Ruchir317** [comment]
Getting connection refused error

**Comment by brandongallagher1999** [comment]
Hello @Fancrafter317, that is because you need to run this via the docker-compose file. The bot is querying the torrent microservice via DNS that docker auto handles.

**Comment by brandongallagher1999** [comment]
Even though the issue is closed, I'm going to include @Rimgelair

**Comment by Ruchir317** [comment]
I ran it via docker compose but it is showing the same erro
![Test](https://user-images.githubusercontent.com/66352423/162235018-b5288e27-137f-400d-8480-f0e8268b31a2.png)
r
