### ISSUE TITLE
hosted bot is down

### ISSUE THREAD

**Issue by kekkodance** [brandongallagher1999/1337x-Bot-Go#15]
it seems like the bot went offline for a few days already, does this mean it's done for?
![image](https://user-images.githubusercontent.com/53054786/166149445-cd9d1837-fb64-423c-84ec-b0cb90a839d5.png)

**Comment by brandongallagher1999** [comment]
Nope, I will redeploy the far stabler bot today. I deleted my discord recently and that's why I haven't been able to follow it's upstatus.

**Comment by kekkodance** [comment]
hope you'll come back in ripped

**Comment by brandongallagher1999** [comment]
Thanks, but I don't think I'll be reinstalling Discord again. If I do on the odd chance, it will only be for managing the bot.

**Comment by brandongallagher1999** [comment]
Deploying today. Just have to spin up a new VM in terraform as I lost the PEM file for SSH :/

**Comment by brandongallagher1999** [comment]
Actually, I found out that my Azure account has been shut down by the previous School email, and I currently do not have the funds to host 1337x. 

This is unfortunate news, but both repos have steps to host the bot on their own @kekkodance

**Comment by brandongallagher1999** [comment]
That's why the bot shut down a few days ago, because that account was killed.

**Comment by Jadensc98** [comment]
I have a bot up using your code, could this be why it's stuck typing and not sending anything in Discord? @brandongallagher1999

**Comment by brandongallagher1999** [comment]
It could be something cloudflare related as was the problem before which is
unfixable on 1337xs website side.

**Comment by kekkodance** [comment]
> It could be something cloudflare related as was the problem before which is unfixable on 1337xs website side.


this was fixed in a recent commit pointed out by #17 @Jadensc98

**Comment by Jadensc98** [comment]
> > It could be something cloudflare related as was the problem before which is unfixable on 1337xs website side.
> 
> this was fixed in a recent commit pointed out by #17 @Jadensc98

Works now, Thanks!
