### ISSUE TITLE
Cannot find Config/config.yaml

### ISSUE THREAD

**Issue by Jadensc98** [brandongallagher1999/1337x-Bot-Go#16]
Hello, when i run the image I'm getting this:

![image](https://user-images.githubusercontent.com/42193375/166463573-5bc69cfe-e3fd-429a-a0e6-113fd79424da.png)

Where is it looking? I created a config file in the config folder in the cloned repo

**Comment by brandongallagher1999** [comment]
Can you screenshot your directory? If you created config.yaml under /config/, this error shouldn't be coming up

**Comment by Jadensc98** [comment]
![image](https://user-images.githubusercontent.com/42193375/166465271-bf719673-f0d5-4d7c-9c2c-3fd3c223e176.png)

and

![image](https://user-images.githubusercontent.com/42193375/166465302-639d0ac9-b674-4fbc-a48f-3ed66a1d2181.png)

**Comment by Jadensc98** [comment]
Wow just realized, sorry im dumb

**Comment by brandongallagher1999** [comment]
There's your problem. Rename config.yml to --> config.yaml
