### ISSUE TITLE
scrambled magnet links

### ISSUE THREAD

**Issue by kekkodance** [brandongallagher1999/1337x-Bot-Go#24]
the few first magnet links given by the bot match their name on the torrent client, but for example, going more than 5. on "far cry" gets you the 8th result as a magnet, the 8. result gets you 10 and so on

**Comment by kekkodance** [comment]
![image](https://user-images.githubusercontent.com/53054786/168255240-746c87b0-a3ba-4de0-8b96-7c4e6319232f.png)
![image](https://user-images.githubusercontent.com/53054786/168255268-0ca04a1e-96eb-4d3e-8fc3-fbb560570a92.png)
![image](https://user-images.githubusercontent.com/53054786/168255324-d0b12d85-e075-46be-a4a1-accd014b3bc2.png)

**Comment by Rimgelair** [comment]
Is it ok if I take a look at this one?

**Comment by brandongallagher1999** [comment]
Yup @Rimgelair

**Comment by kekkodance** [comment]
it's like if the bot had no delay in indexing the links so it goes "too fast" and shits itself

**Comment by kekkodance** [comment]
aany solution yet?

**Comment by brandongallagher1999** [comment]
@Rimgelair

**Comment by kekkodance** [comment]
hmmm

**Comment by kekkodance** [comment]
buump

**Comment by kekkodance** [comment]
hii?

**Comment by brandongallagher1999** [comment]
Brutal. I don't know how busy Rimeglair is but he is handling this ticket haha

**Comment by kekkodance** [comment]
could you... take a look? people are fucking mad in my server that the bot gives scrambled links, some guy got a nosteam release despite clicking another result and almost risked his stuff

**Comment by kekkodance** [comment]
fixed in #26.
