### ISSUE TITLE
Docker Container Error

### ISSUE THREAD

**Issue by Jadensc98** [brandongallagher1999/1337x-Bot-Go#27]
I've recently been getting this error when running the docker container for the bot: `TypeError: Cannot read properties of undefined (reading 'data')` 

The bot has been working perfect until about a few days ago. Would you be familiar with this issue?

**Comment by brandongallagher1999** [comment]
@kekkodance

**Comment by Jadensc98** [comment]
Working now

**Comment by brandongallagher1999** [comment]
Great!
